---
title: "Project Proposal"
author: "Francis Olakangil"
date: "`r Sys.Date()`"
output: html_document
---

# Cryptocurrency Market Data Project

## Project Proposal

I want to use the datasets given from Kaggle's cryptocurrency section, specifically the datasets `coin_gecko_2022-03-16` and `coin_gecko_2022-03-17`. These datasets are about the changes in market data, trade values, and trends over a number of different cryptocurrencies across March 16th and 17th of 2022.

### Questions of Interest

1. Is there a correlation between the market capitalization of the specific cryptocurrency, and the given price it is trading at? Does the cryptocurrency's volatility frequently change the overall market cap?

2. Do changed in currency value between 1-hour segments and 24-hour segments have significant effects on the overall market cap of the currency? What about on the 7-day measuring period?

3. Considering the volatility of cryptocurrency as a whole, does a potential winner in terms of the best cryptocurrency to invest in change between the different measuring periods?

4. Do more prevalent cryptocurrencies, or those with a larger market cap, inherently imply more volatility? How can we measure that using the three measuring periods the datasets give?

### Potential Complications

The data is slightly vague in terms of how it ranks certain cryptocurrencies with declines. Does a currency rocket to the bottom of the list as the least-recommended to invest in just because it has the steepest decline in trade value? Considering that some of the most successful currencies are the most volatile, I would have to recategorize how currencies are sorted, accounting for both trade values and overall market cap. 

I could create a whole project connnecting both datasets across the two days.

## Data

There are 500 rows and 9 columns, or categorical variables for the different currencies. The data traverses the 9 different variables, giving numerical data as to how the trade value of the various currencies changes across the variables.

Link to data if attached files in Sakai submission not working: https://www.kaggle.com/datasets/thedevastator/cryptocurrency-price-market-data/

```{r}
library(tidyverse)
library(mdsr)
library(readr)

setwd("/Users/fran-pellegrino/Library/CloudStorage/OneDrive-LoyolaUniversityChicago/DSCI101/DSCI_Whalen")
#data1 <- read.csv("~/coin_gecko_2022-03-16.csv")
#View(data1)
#attach(data1)
```



